# Model arguments
model_name_or_path: rica40325/lora32_third_step


# Data training arguments
dataset_mixer:
  /workspace/yui/SPIN/new_data/iter0: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 4

# Trainer arguments
bf16: true
beta: 0.1
do_eval: false
evaluation_strategy: "no"
eval_steps: 100
gradient_accumulation_steps: 8
gradient_checkpointing: true
learning_rate: 5.0e-5
log_level: info
logging_steps: 10
lr_scheduler_type: linear
max_length: 2048
max_prompt_length: 2048
num_train_epochs: 3
optim: rmsprop
output_dir: outputs
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
push_to_hub: false
save_strategy: "epoch"
save_total_limit: null
seed: 42
warmup_ratio: 0.1
